language: node_js
node_js:
- stable
addons:
  sauce_connect: true
script:
  - node test/
  - zuul test/
env:
  global:
  - secure: JatUrrYC1TdD5yegvOjLGKUIisbxDUMwzyKYWHO+cYpeFGNRk40FGdKZI3Ci4UDBcVcULAyHJgMAq0FjK8bghdg8L41qH/xBmHfcpfiTZufoOj7KtMO7UdjUAVq4YIRfS1Qrc9Om7DXOxiJeIIkfoUj7FvaCLGpvyWgbdfFnBFY=
  - secure: Bx6iEUyNipZB0QtaBqBpDkIJ8dY4AMYjVFvTQJm4xfpHt5maV8AYjg4glwq7O2GELx7MUjIBg1KsG3uyWbFBd4ZVn3aThv859szIYQB5iZddrbvlW3bZbH3h8RrvRUL6Wj57fRGTGSaOiebMvdSLGaDwXf+xceH4dz67MB1liAM=
