ui: tape
browsers:
  - name: chrome
    version: 44..latest
    platform: Mac 10.10
  - name: firefox
    version: 40..latest
    platform: Mac 10.10
  - name: ie
    version: 10..latest
  - name: iphone
    version: 9.0..latest
    platform: Mac 10.10
  - name: android
    version: 5.1..latest
    platform: Linux