ui: tape
browsers:
  - name: chrome
    version: 42..latest
    platform: Mac 10.10
  - name: firefox
    version: 39..latest
    platform: Mac 10.10
  - name: ie
    version: 9..latest
  - name: iphone
    version: 8.4..latest
    platform: Mac 10.10
  - name: safari
    version: 8..latest
    platform: Mac 10.10
  - name: android
    version: 5.0..latest
    platform: Linux